name: Build nightly

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc
    name: Compile ROM
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build GRRLIB
        run: |
          cd GRRLIB/
          dkp-pacman --sync --needed --noconfirm libfat-ogc ppc-libpng ppc-freetype ppc-libjpeg-turbo ppc-libvorbisidec
          make -C GRRLIB clean all install
      - name: Make application
        run: |
          make
      - name: Prepare for build publishing
        run: |
          mkdir -p out/rom
          mkdir -p out/rom/resources
          mkdir -p out/rom/resources/songs
          mkdir -p out/rom/user_levels
          cp -r data/hbc/. out/rom/
          cp -r data/songs/. out/rom/resources/songs/
          cp gdwii.dol out/rom/boot.dol
      - name: Publish build to GH Actions
        uses: actions/upload-artifact@v4
        with:
          path: out/rom
          name: wiidash
