name: Build nightly

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc
    name: Compile ROM
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Make application
        run: |
          make
      - name: Prepare for build publishing
        run: |
          mkdir -p out/rom
          cp build/gdwii.dol out/rom
      - name: Publish build to GH Actions
        uses: actions/upload-artifact@v4
        with:
          path: out/rom
          name: gd-wii
